<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="DESKTOP-PTK84VK" name="testCase.TasksTest" tests="8" failures="0" timestamp="2021-06-13T22:37:00 IST" time="40.740" errors="1">
  <testcase name="CorrectUnameCorrectPwd" time="20.507" classname="testCase.TasksTest"/>
  <system-out/>
  <testcase name="tasksmenucheck" time="5.491" classname="testCase.TasksTest"/>
  <system-out/>
  <testcase name="addTask" time="8.265" classname="testCase.TasksTest"/>
  <system-out/>
  <testcase name="verifyTask" time="2.252" classname="testCase.TasksTest"/>
  <system-out/>
  <testcase name="statusChange" time="3.371" classname="testCase.TasksTest"/>
  <system-out/>
  <testcase name="delete" time="0.854" classname="testCase.TasksTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at utilities.AlertHelper.alertAccept(AlertHelper.java:9)
at testCase.TasksTest.delete(TasksTest.java:144)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- delete -->
  <system-out/>
  <testcase name="fileDownload" classname="testCase.TasksTest">
    <skipped/>
  </testcase> <!-- fileDownload -->
  <system-out/>
  <testcase name="fileUpload" classname="testCase.TasksTest">
    <skipped/>
  </testcase> <!-- fileUpload -->
  <system-out/>
</testsuite> <!-- testCase.TasksTest -->
